Bt17 implementation of login class alex myrko
alexmyrko/Bug-tracker pull request #1
Opened 2020-12-25 09:08 UTC by alexmyrko

2020-12-25 09:52 UTC, sloboda89 commented
Код з поточно гілки не компілюється. Клас Register повинний містити імплементацію метода execute()

2020-12-25 10:04 UTC, sloboda89 requested changes

2020-12-25 10:04 UTC, sloboda89 commented on src/com/bugtracker/login/Login.java
>  // You need implement interface method for looging on an existing user
Деяка непослідовність в неймінгу класів Login/Logging. Пропонував би перейминувати інтерфейс Logging в Login, а клас Login в LoginImpl.

2020-12-25 10:04 UTC, sloboda89 commented on src/com/bugtracker/login/Login.java
>  // You need implement interface method for looging on an existing user
Будь ласка, перемістіть дерикторію /resources в дерикторію /src. Розбиття на пакети має сенс лише для коду.

2020-12-25 10:04 UTC, sloboda89 commented on src/com/bugtracker/login/Login.java
>  // You need implement interface method for looging on an existing user
Згідно до вимог проекту дані повинні зберігатися в колекціях, або інмеморі базі даних (In-mem collection, or *in-mem DB (H2)). Але не в проперті файлі. В файлі можна зберегти тестові дані і на старті завантажити їх в колекцію, але маніпуляцію з даними повинні відбуватись уже з колекціями даних.

2020-12-25 10:04 UTC, sloboda89 commented on src/com/bugtracker/login/Login.java
>  // You need implement interface method for looging on an existing user
Якщо введено некоректного користувача чи пароль метод execute() поверне null і це приведе до `NullPointerException `тут:
`System.out.println("Logged user: " + currentUser.getUserName());`

2020-12-29 09:43 UTC, alexmyrko commented on src/com/bugtracker/login/Login.java
>  // You need implement interface method for looging on an existing user
Змінив структуру згідно вимог

2020-12-29 13:27 UTC, alexmyrko commented on src/com/bugtracker/login/Login.java
>  // You need implement interface method for looging on an existing user
Зміни згідно зауважень вніс

2020-12-29 15:12 UTC, sloboda89 commented
Перш за все є два нюанси:
- код не компілюється (вирішується додаванням `return LOGIN;` от [тут](https://github.com/alexmyrko/Bug-tracker/pull/1/files#diff-c890ea05df68b428abe641d8599ddb1c2ac1b0e7de2bd50e551d75e63dd3494cL10))
- конфліктів з main стало ще більше. Потрібно зробити `git rebase main` і вирішити конфлікти.

Але після того як вирішити помилку компіляції код працює і це вже чудово.

2020-12-29 16:05 UTC, sloboda89 commented
В цілому код робочий і після виправлення коментарів може бути змерджений.

2020-12-29 17:03 UTC, alexmyrko commented
> В цілому код робочий і після виправлення коментарів може бути змерджений.

2020-12-29 17:04 UTC, alexmyrko commented
> > В цілому код робочий і після виправлення коментарів може бути змерджений.

2020-12-29 17:08 UTC, alexmyrko commented
> > В цілому код робочий і після виправлення коментарів може бути змерджений.



> Перш за все є два нюанси:
> 
> * код не компілюється (вирішується додаванням `return LOGIN;` от [тут](https://github.com/alexmyrko/Bug-tracker/pull/1/files#diff-c890ea05df68b428abe641d8599ddb1c2ac1b0e7de2bd50e551d75e63dd3494cL10))
> * конфліктів з main стало ще більше. Потрібно зробити `git rebase main` і вирішити конфлікти.
> 
> Але після того як вирішити помилку компіляції код працює і це вже чудово.

Реалізацію класу Operation робить Макс Проценко, тому я його і залишив в пустому вигляді

2021-01-01 11:01 UTC, sloboda89 approved these changes
Залишив декілька дрібних коментарів, після того як вони будуть вирішені, можна мерджити в main. 

P.S. Також нагадую що потрібно вирішити конфлікти.

2021-01-01 11:01 UTC, sloboda89 commented on src/com/bugtracker/BugTracker.java
> +    private Map<String, User> users = new HashMap<>();
Згідно вимог система має бути побудованим на базі трьох шарової архітектури. Відповідно до ціього підходу доступ до даних має відбуватись через data access object (DAO). Відповідно потрібно створити такий шар і перенести код який має відношення до збереження і маніпуляції з даними туди.

2021-01-01 11:01 UTC, sloboda89 commented on src/com/bugtracker/login/LoginImpl.java
> +        for (Map.Entry<String, User> entry : bugTracker.getUsers().entrySet())
Перебір списку всіх користувачів на кожній спробі логіну доволі дорога операція. Краще просто діставати користувача з Map-и просто по ключу:
`User user = bugTracker.getUsers().get(userName);`

2021-01-01 11:01 UTC, sloboda89 commented on src/com/bugtracker/BugTracker.java
> +    public static int counter = 1;
Виглядає, щоця змінна тут непотрібна і її можна видалити.

2021-01-01 11:01 UTC, sloboda89 commented on src/com/bugtracker/dao/UsersDaoImpl.java
> +public class UsersDaoImpl implements UsersDAO {
👍

2021-01-01 11:01 UTC, sloboda89 commented on src/com/bugtracker/view/View.java
> +        usersDAO = UsersDaoImpl.getInstance();
UsersDAO тут непотрібне.
Будь ласка, додайте в LoginImpl метод і викликайте його тут.
```
@Override
public void initUsers() {
    usersDAO.initUsers();
}
```

2021-01-01 11:01 UTC, sloboda89 commented on src/com/bugtracker/commands/LoginImpl.java
> +        for (Map.Entry<String, User> entry : usersDAO.getAllUsers().entrySet())
Будь ласка, додайте в UserDao метод getUserByUsername і використовуйте його тут замість перебору всіх користувачів.
```
@Override
public User getUserByUsername(String username) {
    return users.get(username);
}
```

2021-01-01 13:47 UTC, alexmyrko commented on src/com/bugtracker/view/View.java
> +        usersDAO = UsersDaoImpl.getInstance();
Але у нас з самого початку є вибір операції: Login чи Register. Відповідно, потрібно продублювати метод initUsers() в обох класах, залежно від вибору операції, бо ми спочатку можемо захотіти зареєструвати нового користувача, а не залогінитись.  Тому я цей метод спочатку викликаю в класі View.   Але порадь як зробити краще.

2021-01-01 17:42 UTC, sloboda89 commented on src/com/bugtracker/view/View.java
> +        usersDAO = UsersDaoImpl.getInstance();
Проблема відпаде якщо викликати initUsers() в конструкторі, а не в методі login().

2021-01-02 08:26 UTC, sloboda89 commented on src/com/bugtracker/view/View.java
> +        usersDAO.initUsers();
Будь ласка, не використовуйте тут DAO. Додайте в LoginImpl метод і викликайте його тут.
```
@Override
public void initUsers() {
    usersDAO.initUsers();
}
```

2021-01-02 08:45 UTC, sloboda89 commented on src/com/bugtracker/commands/LoginImpl.java
> +        usersDAO.initUsers();
👍

2021-01-02 20:45 UTC, merged