Refactored structure using TicketsServiceImpl class
alexmyrko/Bug-tracker pull request #6
Opened 2021-01-04 12:02 UTC by alexmyrko

Refactored structure: 
1 - added TicketServiceImpl class with TicketService interface. 
2 - deleted CreateImpl, EditImpl, PrintImpl and ExitImpl classes  
3 - initialized first 3 tickets in TicketsDaoImpl

2021-01-04 13:58 UTC, sloboda89 requested changes

2021-01-04 13:58 UTC, sloboda89 commented on src/com/bugtracker/dao/TicketsDaoImpl.java
> +        tickets.put(id, ticket);
Пропоную не передавати id сюди як параметер, а інкрементити його тут.
```
int id = counter++;
ticket.setId(id);
tickets.put(id, ticket);
```

2021-01-04 13:58 UTC, sloboda89 commented on src/com/bugtracker/dao/TicketsDaoImpl.java
> +        tickets.put(id, new Ticket(id, "Creating project structure", UsersDaoImpl.getInstance().getUserByLogin("alex"),
Тут краще використовувати метод addTicket(Ticket ticket);
```
addTicket(new Ticket("Implementing Register class", UsersDaoImpl.getInstance().getUserByLogin("alex"),
                UsersDaoImpl.getInstance().getUserByLogin("max"), Status.PLANNED, Priority.MEDIUM, 24));
```
Попередньо прибравши id з конструктора Ticket.

2021-01-04 13:58 UTC, sloboda89 commented on src/com/bugtracker/dao/TicketsDaoImpl.java
> +    int counter = 1;
Каунтер може бути private

2021-01-04 13:58 UTC, sloboda89 commented on src/com/bugtracker/commands/TicketServiceImpl.java
> +    public void create(User currentUser) {
Не потрібно передавати сюди поточного користувача як параметр. Додайте, будь ласка, в UserDAO методи setCurrentUser(User user) і getCurrentUser() і використовуйте їх тут.

2021-01-04 13:58 UTC, sloboda89 commented on src/com/bugtracker/model/Ticket.java
> +        date = new Date();
Використовуйте, будь ласка, java.time.LocalDateTime замість java.util.Date.

2021-01-04 13:58 UTC, sloboda89 commented on src/com/bugtracker/commands/TicketServiceImpl.java
> +        System.out.println("Press Enter button to print all tickets or enter login to print certain user tickets:");
Весь ввід/вивід має бути на рівні View.

2021-01-04 13:58 UTC, sloboda89 commented on src/com/bugtracker/commands/TicketServiceImpl.java
> +    private TicketsDAO ticketsDAO;
ticketsDAO може бути final

2021-01-04 13:58 UTC, sloboda89 commented on src/com/bugtracker/commands/TicketService.java
> +    public void create(User currentUser);
Модифікатори доступу не мають сенсу в інтерфейсах.

2021-01-04 13:58 UTC, sloboda89 commented on src/com/bugtracker/view/View.java
> +    private User currentUser = null;
Це не повинно зберігатись на рівні View. Перенесіть це у UserDAO, будь ласка.

2021-01-04 16:54 UTC, alexmyrko commented
Виправив згідно зауважень в pull request

2021-01-04 17:12 UTC, sloboda89 requested changes

2021-01-04 17:12 UTC, sloboda89 commented on src/com/bugtracker/model/Ticket.java
> +    private int totalTime = timeEstimated;
Присвоєння тут не має сенсу timeEstimated тут завжди рівне 0

2021-01-04 17:12 UTC, sloboda89 commented on src/com/bugtracker/view/View.java
> +        usersDao = UsersDaoImpl.getInstance();
Тут не має бути dao, View шар нічо не має знати про DAO, Тут має бути new TicketServiceImpl(), new LoginImpl() і new RegisterImpl(). Віповідні методи (getLogin(), getRegister(), getTicketService()) з DAO потрібно прибрати.

2021-01-05 08:19 UTC, sloboda89 commented on src/com/bugtracker/commands/LoginImpl.java
> +            UsersDaoImpl.getInstance().setCurrentUser(currentUser);
Тут можна використовувати usersDAO замість UsersDaoImpl.getInstance()

2021-01-05 08:31 UTC, sloboda89 approved these changes

2021-01-05 08:48 UTC, merged