Implemented print methods
alexmyrko/Bug-tracker pull request #9
Opened 2021-01-07 10:58 UTC by maksim-protsenko

review needed

2021-01-07 12:33 UTC, sloboda89 requested changes

2021-01-07 12:33 UTC, sloboda89 commented on src/com/bugtracker/commands/TicketServiceImpl.java
> +                    System.out.println(ticket.toString());
toString є зайвим тут. System.out.println викличе його сам

2021-01-07 12:33 UTC, sloboda89 commented on src/com/bugtracker/commands/TicketServiceImpl.java
> +            System.out.println("This assignee isn`t exist!\n");
Правильно було б кинути тут виключення і обробити його у View

2021-01-07 12:33 UTC, sloboda89 commented on src/com/bugtracker/commands/TicketServiceImpl.java
> +                    System.out.println(ticket.toString());
Було б правильно відфільтрувати тут тікети за assignee. І повернути їх до  View

2021-01-07 12:33 UTC, sloboda89 commented on src/com/bugtracker/commands/TicketServiceImpl.java
> +            System.out.println(ticket.toString());
Вивід має відбуватись у View

2021-01-07 18:05 UTC, maksim-protsenko commented
reworked

2021-01-08 08:38 UTC, sloboda89 approved these changes
Залишив декілька дрібних коментарів, а так все ок.

2021-01-08 08:38 UTC, sloboda89 commented on src/com/bugtracker/commands/TicketServiceImpl.java
> +            System.out.println(ticket);
Вивід має бути в View

2021-01-08 08:38 UTC, sloboda89 commented on src/com/bugtracker/commands/TicketServiceImpl.java
> +    public ArrayList<Ticket> getTicketsByAssignee(User user) {
Тут краще вказувати інтерфейс public `List<Ticket> getTicketsByAssignee(User user)`

2021-01-08 08:38 UTC, sloboda89 commented on src/com/bugtracker/commands/TicketServiceImpl.java
> +        ArrayList<Ticket> assigneeTickets = new ArrayList<>();
Тут краще вказувати інтерфейс `List<Ticket> assigneeTickets = new ArrayList<>();`

2021-01-08 08:38 UTC, sloboda89 commented on src/com/bugtracker/commands/UserServiceImpl.java
> +            return usersDAO.getUserByLogin(login);
Зайвий таб

2021-01-08 08:38 UTC, sloboda89 commented on src/com/bugtracker/view/View.java
> +        ArrayList<Ticket> assigneeTickets;
`List<Ticket> assigneeTickets;`

2021-01-08 08:38 UTC, sloboda89 commented on src/com/bugtracker/view/View.java
> +                    User user;
такі великі блоки коду краще виносити в окремі методи

2021-01-08 13:36 UTC, merged